whl file check

diff --git a/examples/reverse-proxy/mnist/run-all b/examples/reverse-proxy/mnist/run-all
--- a/examples/reverse-proxy/mnist/run-all
+++ b/examples/reverse-proxy/mnist/run-all
@@ -19,7 +19,7 @@ echo "APLS IP: "${APLS_IP}
 
 Host_IP=$2
 [[ -z "$2" ]] && { echo "IP address of the Host 1 is empty" ; exit 1; }
-echo "HOST 1 IP: "${Host_IP_1}
+echo "HOST 1 IP: "${Host_IP}
 
 # Checks for the wait time of sn. If not passed by default it waits for 5 minutes 
 [[ -n "${3}" ]] && snWaitTime=${3} || snWaitTime="5m"
@@ -34,6 +34,16 @@ else
     echo "It is mandatory to run these scripts in the base(swarm-learning) directory of this repository. Please cd(change directory) to base directory."
     exit 1; 
 fi
+
+if [[ -f "$(pwd)/lib/swarmlearning-client-py3-none-manylinux_2_24_x86_64.whl" ]]
+then
+    echo "Wheel file found in the desired location."
+else
+    echo "It is required to keep the whl file and its symbolic link in the lib folder of this base(swarm-learning) directory."
+    exit 1; 
+fi
+
+
 
 reverseProxyDir=$(pwd)/examples/reverse-proxy
 reverseProxyMnistDir=$(pwd)/examples/reverse-proxy/mnist
